language: python
matrix:
  include:
    - python: 2.7
      dist: xenial
    - python: 3.2
      dist: trusty
    - python: 3.3
      dist: trusty
    - python: 3.4
      dist: xenial
    - python: 3.5
      dist: xenial
    - python: 3.6
      dist: xenial
    - python: 3.7
      dist: xenial
install: ""
script: test/run_tests
